### ISSUE TITLE
ricaricamento all'accettazione

### ISSUE THREAD

**Issue by giovinova** [Corsidia/it_cookie_law#2]
Salve volevo saper se è possibile attivare il ricaricamento della pagina dopo l'accettazione

**Comment by progressify** [comment]
Ho appena creato una pull request per questa funzionalità, è passato qualche anno ma spero che sia cosa gradita.
Attendo approvazione da parte di @darmenise

**Comment by duarme** [comment]
Certo che è cosa gradita! ho commentato la tua PR poco fa. Per favore aggiungila anche nel README e mergiamo 👍

**Comment by progressify** [comment]
Non vedo nessun commento nella pull request, comunque, al readme aggiungo le istruzioni per configurare questa nuova feature?

**Comment by duarme** [comment]
Sorry, sono troppo abituato a Bitbucket... qui devo mandare la review esplicitamente, l'ho appena pubblicata.

**Comment by progressify** [comment]
chiudi pure la relative issue :)

**Comment by duarme** [comment]
Implemented by #5
