### ISSUE TITLE
Salve potete inserire anche il bottone per negare i cookies?

### ISSUE THREAD

**Issue by SalvoMds** [Corsidia/it_cookie_law#4]

**Comment by duarme** [comment]
Ciao Salvo, è open source, si accettano pull request :)

**Comment by progressify** [comment]
Con il bottone `Nega` semplicemente la libreria non dovrebbe fare nessuna operazione.
Però immagino che ad ogni nuova pagina visitata mostrerebbe di nuovo il messaggio dei cookies, visto che l'utente non accetta nemmeno i cookie tecnici per consentire di memorizzare la non accettazione. 

Corretto? 
Se ho ben inteso il funzionamento provvedo ad implementare anche questa feature.

**Comment by duarme** [comment]
Oppure dovrebbe salvare la scelta dell'utente (cioè il fatto che ha negato il consenso) e quindi far sparire il banner (magari sostituendolo con un pulsantino in un angolo se sceglie di cambiare idea) e, soprattutto, a quel punto dovrebbe evitare l'accettazione con lo scroll e non dovrebbe mai attivare nessun componente di terza parte. Secondo la cookie law è ok salvare i cookie tecnici di questo tipo, non serve il consenso, basta specificarlo nella cookie policy. 

La cosa sulla quale sono meno ferrato, invece, è se sia ancora legale accettare con uno scroll. Secondo un [chiarimento del garante della privacy, ved. punto 5](https://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/4006878) dovrebbe essere legale purché chiaramente indicato (per questo c'è il tempo di attesa di qualche secondo prima di poter accettare così).

**Comment by progressify** [comment]
Io so che non è legale, il consenso deve essere attivo da parte dell'utente, infatti volevo modificare anche questo comportamento. In realtà credevo che questa cosa fosse già implementata (cioè la possibilità di scegliere tra consenso attivo o tramite scroll), ma non ne ho trovato traccia

**Comment by duarme** [comment]
Però hai letto il chiarimento del Garante per la privacy che ho linkato? Dice che lo scroll va bene, purché sia esplicito. Per renderlo esplicito ho aggiunto un tempo di attesa di qualche secondo (impostabile) e, ovviamente, bisogna scrivere nel banner che effettuando lo scroll si accettano i cookie. Lo so che i pareri, anche legali, su questo punto un si dividono ma la prima autorità responsabile è il Garante per la privacy e lui dice chiaramente che va bene. Se vuoi aggiungere un'altra funzionalità, purché opzionale, per me va bene. In quel caso aggiungiti anche agli autori elencati in fondo al README :)

**Comment by progressify** [comment]
@darmenise grazie per aver accettato la pull request, ora puoi chiudere anche la relativa issue :)

**Comment by duarme** [comment]
Fixed by #6

**Comment by duarme** [comment]
Ci stavo provando ma github ha qualche problema! ved.
https://www.githubstatus.com/
