### ISSUE TITLE
Script non funzionante

### ISSUE THREAD

**Issue by ongaroandrea** [Corsidia/it_cookie_law#7]
Salve,
ho scaricato lo script,l'ho messo all'interno della cartella js del sito e ho inserito lo script nell'header insieme al jquery. 
Successivamente ho modificato l'src dell'iframe con il tag data-blocked e il tag src è ora così (src="#"). Il blocco sarebbe da applicare all'iframe per la mappa di google, ma non viene bloccata. 
Per testare il reale funzionamento ho provato anche ad inserire uno script di prova
```
<script type='text/blocked'>
  alert('sono bloccato preventivamente');
</script>
```
ma viene mostrato subito all'apertura della pagina

**Comment by duarme** [comment]
Ho provato adesso su Chrome e funziona 🤔  mi viene il dubbio che su alcuni browser quello script potrebbe essere eseguito lo stesso... che browser stai utilizzando? 

Sei sicuro che non hai già accettato i cookie? Se li hai accettati la prima volta lo script sblocca tutto al caricamento della pagina. Prova a cancellare i cookie, lo script viene eseguito lo stesso al caricamento?

Qui hai un html di test con tanti esempi, ho provato poco fa e non viene eseguito nessuno prima dello sblocco: https://raw.githubusercontent.com/Corsidia/it_cookie_law/master/esempi.html

**Comment by ongaroandrea** [comment]
Ho cancellato i cookie e ho provato a ricaricare la pagina. Adesso sembra funzioni, ma solo per qualche secondo dopo i quali la pagina si ricarica in automatico da sola e penso che si accettino in automatico i cookie.
Il sito è valisi.it, se vuoi provare a vedere anche te. Ho provato sia su firefox che su chrome e il risultato è sempre lo stesso. Potrebbe andare in conflitto con qualche plugin? Il sito web non è mio quindi non saprei cosa potrebbe essere, mi hanno chiesto solo di metterlo a posto per la questione dei cookie

**Comment by duarme** [comment]
Se fai lo scroll dopo 2 secondi li accetta. Puoi disattivare l'accettazione con scroll settando la variabile `explicitConsent`.

Per l'iframe ti consiglio di non settare `src="#"`, altrimenti ti ripete tutta la pagina all'interno dell'iframe finché non accetti i cookie. Piuttosto fallo puntare a un file html tipo questo:

`<iframe src="/blocked.html" data-blocked="https://www.google.com/maps/embed...`

```
<!-- blocked.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Cookie bloccati</title>
  </head>
  <body>
     Per vedere questo contenuto devi accettare i cookie.
  </body>
</html>
```

O qualcosa del genere :)

**Comment by ongaroandrea** [comment]
Che stupido, avevo letto velocemente il js e non ci avevo fatto caso.
Grazie mille per la risposta e anche per la velocità.
Buone feste
